name: Alipay Cloud Devops Codescan
on:
  push:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: codeScan
        uses: xuqiu/alipay-cloud-devops-codescan@main
        with:
          parent_uid: '14955076510547972'
          private_key: 'PpaeApOVW+ygrCC5pKYJaOXFY1kQpG7kdr7KYS5VshgPJNlcKL7YU6KuEASY2PGIEG131TT2FUutRmnfPOMJLPbx06xReel8zIDMnLqQwuSh9d2f3yydS15bFkzpUaANKzOAivY7dTBeTZTkpkmveYqSLaPXHqgegXzYDOrRCSw='
