# github action 试用
name: Java CI

on:
  push: # 触发事件
    branches: [ "master" ] #限制生效分支
  pull_request:
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest #镜像
    steps: #执行步骤
      - name: Nightfall DLP Action
        uses: nightfallai/nightfall_dlp_action@v2.1.0
        env:
          NIGHTFALL_API_KEY: ${{ secrets.NIGHTFALL_API_KEY }}
          #NF-afZIao2GK4mZJOId3pX3nUnj9IDQ3fo1
          GITHUB_TOKEN: ${{ secrets.DLP_GITHUB_TOKEN }}
          #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
          EVENT_BEFORE: ${{ github.event.before }}

