# github action 试用
name: Java CI

on:
  push: # 触发事件
    branches: [ "master" ] #限制生效分支
  pull_request:
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest #镜像
    steps: #执行步骤
      - name: Output Log
        run: |
          echo "This is a log ${{ secrets.NIGHTFALL_API_KEY: -4}}"
          echo "That is a log ${{secrets.GITHUB_TOKEN: -4}}"

      - name: Checkout Repo Action
        uses: actions/checkout@v2

      - name: Nightfall DLP Action
        uses: nightfallai/nightfall_dlp_action@v2.1.0
        env:
          NIGHTFALL_API_KEY: ${{ secrets.NIGHTFALL_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_BEFORE: ${{ github.event.before }}
    permissions:
      checks: write
      contents: read
