name: Greeting on variable day

on:
  pull_request_target:
  pull_request:
  push:

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: "echo $GITHUB_REPOSITORY 111 ${{ github.event.pull_request.head.repo.url }} 222 $GITHUB_BASE_REF 333 $GITHUB_HEAD_REF bbb ${{vars.APP_ID}} ccc ${{secrets.ALI_PID}} Today is $Greeting!"
        env:
          First_Name: Mona