name: Greeting on variable day

on:
  pull_request_target:
  push:

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: "echo $GITHUB_REPOSITORY aaa $GITHUB_BASE_REF aaa $GITHUB_HEAD_REF bbb ${{vars.APP_ID}}  Today is $Greeting!"
        env:
          First_Name: Mona